import { clsx, type ClassValue } from 'clsx';
import { extendTailwindMerge } from 'tailwind-merge';

const mergeClasses = extendTailwindMerge({
  extend: {
    theme: {
      color: [
        'canvas',
        'raised',
        'pressed',
        'surface',
        'inset',
        'line',
        'line-strong',
        'fg',
        'fg-2',
        'fg-3',
        'fg-4',
        'ok',
        'warn',
        'bad',
        'info',
        'accent',
        'accent-dim',
        'accent-ink',
        'interactive',
        'interactive-strong',
        'interactive-light',
        'interactive-soft',
      ],
      font: ['sans', 'serif', 'display', 'ui', 'arabic', 'mono', 'num'],
      radius: [
        'sm',
        'compact',
        'DEFAULT',
        'menu',
        'lg',
        'dialog',
        'xl',
        'full',
      ],
      shadow: ['popover', 'menu', 'segment', 'drawer'],
      text: [
        '3xs',
        '3xs-plus',
        '2xs',
        '2xs-plus',
        'xs',
        'xs-plus',
        'sm',
        'sm-plus',
        'base',
        'base-plus',
        'md',
        'md-plus',
        'lg',
        'lg-plus',
        'xl',
        'xl-plus',
        '2xl',
        '2xl-plus',
        '3xl',
        '3xl-plus',
        '4xl',
        '5xl',
        '6xl',
        '7xl',
        '8xl',
        '9xl',
        '10xl',
        '11xl',
        '12xl',
      ],
    },
  },
});

export function cn(...inputs: ClassValue[]) {
  return mergeClasses(clsx(inputs));
}
