import {
  Activity,
  AlertTriangle,
  ArrowUpRight,
  ArrowRight,
  Bell,
  Bolt,
  Building2,
  CalendarDays,
  ChartNoAxesColumn,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  Clock3,
  Coins,
  DollarSign,
  Download,
  Eye,
  Folder,
  Globe,
  Grid2X2,
  HelpCircle,
  Home,
  Inbox,
  Layers3,
  LayoutDashboard,
  MapPin,
  Megaphone,
  Menu,
  Moon,
  MoreHorizontal,
  PieChart,
  Receipt,
  RefreshCw,
  Search,
  ShoppingCart,
  Sparkles,
  Settings,
  Shield,
  Star,
  Sun,
  Target,
  Trash2,
  TrendingUp,
  User,
  Users,
  WalletCards,
  X,
  XCircle,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react';

const icons = {
  activity: Activity,
  'alert-triangle': AlertTriangle,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  bell: Bell,
  bolt: Bolt,
  building: Building2,
  calendar: CalendarDays,
  cart: ShoppingCart,
  chart: ChartNoAxesColumn,
  check: Check,
  'check-circle': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  clock: Clock3,
  close: X,
  coins: Coins,
  dashboard: LayoutDashboard,
  dollar: DollarSign,
  dots: MoreHorizontal,
  download: Download,
  eye: Eye,
  folder: Folder,
  globe: Globe,
  grid: Grid2X2,
  help: HelpCircle,
  home: Home,
  inbox: Inbox,
  layers: Layers3,
  'map-pin': MapPin,
  megaphone: Megaphone,
  menu: Menu,
  moon: Moon,
  pie: PieChart,
  receipt: Receipt,
  refresh: RefreshCw,
  search: Search,
  settings: Settings,
  shield: Shield,
  sparkle: Sparkles,
  star: Star,
  sun: Sun,
  target: Target,
  trash: Trash2,
  trend: TrendingUp,
  user: User,
  users: Users,
  wallet: WalletCards,
  'x-circle': XCircle,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;

type IconProps = Omit<LucideProps, 'name'> & { name: IconName };

export function Icon({ name, ...props }: IconProps) {
  const Glyph = icons[name];
  return <Glyph aria-hidden="true" strokeWidth={1.6} {...props} />;
}
