import {
  Activity,
  ArrowUpRight,
  ArrowRight,
  Bell,
  Bolt,
  CalendarDays,
  ChartNoAxesColumn,
  Check,
  ChevronDown,
  ChevronRight,
  Clock3,
  Coins,
  Folder,
  Grid2X2,
  Inbox,
  Layers3,
  LayoutDashboard,
  Menu,
  Moon,
  RefreshCw,
  Search,
  ShoppingCart,
  Sparkles,
  Settings,
  Shield,
  Star,
  Sun,
  TrendingUp,
  Users,
  WalletCards,
  X,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react';

const icons = {
  activity: Activity,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  bell: Bell,
  bolt: Bolt,
  calendar: CalendarDays,
  cart: ShoppingCart,
  chart: ChartNoAxesColumn,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  clock: Clock3,
  close: X,
  coins: Coins,
  dashboard: LayoutDashboard,
  folder: Folder,
  grid: Grid2X2,
  inbox: Inbox,
  layers: Layers3,
  menu: Menu,
  moon: Moon,
  refresh: RefreshCw,
  search: Search,
  settings: Settings,
  shield: Shield,
  sparkle: Sparkles,
  star: Star,
  sun: Sun,
  trend: TrendingUp,
  users: Users,
  wallet: WalletCards,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;

type IconProps = Omit<LucideProps, 'name'> & { name: IconName };

export function Icon({ name, ...props }: IconProps) {
  const Glyph = icons[name];
  return <Glyph aria-hidden="true" strokeWidth={1.6} {...props} />;
}
